### ISSUE TITLE
(TypeScript) Type definitions are incomplete for sortable tables.

### ISSUE THREAD

**Issue by AlexKvazos** [TanStack/react-table#2970]
**Describe the bug (required)**
Some type definitions are incomplete -- in the column for example.
`Property 'getSortByToggleProps' does not exist on type 'HeaderGroup<object>'.ts(2339)`
`Property 'isSorted' does not exist on type 'HeaderGroup<object>'.ts(2339)`
`Property 'isSortedDesc' does not exist on type 'HeaderGroup<object>'.ts(2339)`

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/react-table-incomplete-types-x1es6

**Steps To Reproduce (required)**
Try to use `useSortBy` on `react-table` and consume the `getSortByToggleProps` function or `isSorted` and `isSortedDesc` properties on a TypeScript project.

**Expected behavior (Recommended)**
The types shouldn't error

**Screenshots**
![Screen Shot 2021-01-05 at 20 55 25](https://user-images.githubusercontent.com/4448627/103723744-57b47680-4f98-11eb-9175-bb2379b1ccef.png)

This bug was reported without any information before and noticed they were also using TypeScript so I could only figure it was TypeScript specific.
https://github.com/tannerlinsley/react-table/issues/1481

**Comment by samyan** [comment]
I had a similar issue with another plugin. The solution i got, was creating folder called **types** in **/src** directory and then creating a file called **react-table-config.d.ts**. Then put the definitions that you can find in: [types/react-table](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table).

Now you can check:
![image](https://user-images.githubusercontent.com/3801362/103941340-fd99e980-512e-11eb-9e36-0bc47d6c6f42.png)

Example:
https://codesandbox.io/s/react-table-incomplete-types-forked-0hdd1

Regards.

**Comment by AlexKvazos** [comment]
Interesting, seems kinda hacky -- I wonder why its not part of the @types/react-table package in npm.

Thank you anyhow @samyan

**Comment by samyan** [comment]
> Interesting, seems kinda hacky -- I wonder why its not part of the @types/react-table package in npm.
> 
> Thank you anyhow @samyan

Ni idea pero estuve días dando vueltas y al final la solución más óptima fue esa.  No hay de que.

Saludos.

**Comment by jamieweavis** [comment]
After some digging it appears that this is expected behaviour of the **@types/react-table** package, and it has documentation on how to include types for the table plugins that you are using, not ideal but presumably this is because the plugins are optional...

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table#configuration-using-declaration-merging

**Comment by jamieweavis** [comment]
After some digging it appears that this is expected behaviour of the `@types/react-table` package, and it has documentation on how to include types for the table plugins that you are using, not ideal but presumably this is because the plugins are optional...

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table#configuration-using-declaration-merging

**Comment by yotam707** [comment]
Had this issue also, would love a resolution from the maintainers because setting it up locally doesn't scale too well with changes being made for this library.

**Comment by samyan** [comment]
> After some digging it appears that this is expected behaviour of the `@types/react-table` package, and it has documentation on how to include types for the table plugins that you are using, not ideal but presumably this is because the plugins are optional...
> 
> https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table#configuration-using-declaration-merging

https://github.com/tannerlinsley/react-table/issues/2970#issuecomment-756364081

**Comment by nikaupp** [comment]
> 
> 
> After some digging it appears that this is expected behaviour of the `@types/react-table` package, and it has documentation on how to include types for the table plugins that you are using, not ideal but presumably this is because the plugins are optional...
> 
> https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table#configuration-using-declaration-merging

In all fairness, the plugins don't feel all that optional as they are included in base package.

**Comment by dkumar431** [comment]
> https://codesandbox.io/s/react-table-incomplete-types-forked-0hdd1

@samyan 
The sandbox link seems to be not working. I am facing the same issue with ts.  After creating a type defination file also I am getting the below error 
`Parameter 'headerGroup' implicitly has an 'any' type.ts(7006)`

**Comment by samyan** [comment]
> > https://codesandbox.io/s/react-table-incomplete-types-forked-0hdd1
> 
> @samyan
> The sandbox link seems to be not working. I am facing the same issue with ts. After creating a type defination file also I am getting the below error
> `Parameter 'headerGroup' implicitly has an 'any' type.ts(7006)`

Updated:

https://codesandbox.io/s/react-table-incomplete-types-fixed-2r4us

**Comment by markoromandic** [comment]
I have an issue as well, for some reason even after declaring types for useSort i still get an error `Property 'isSorted' does not exist on type 'HeaderGroup<object>'` . What is more even strange is that after declaring types for useSort VS Code does says anymore that property does not exist, but react app still has an issue

**Comment by donnfelker** [comment]
Note for anyone having this problem. I just fought this for a number of hours and almost abandoned TS until I realized I had put the `react-table-config.d.ts` in the wrong location. My project looks like this: 

```
/ 
 - /api
 - /client
   - /src
```

I needed this in my client app. I placed it in `/client/types/react-table-config.d.ts` and it did not work. Once I moved it into `/client/src/types/` everything started working. Hope that helps someone.

**Comment by pedrogallon** [comment]
@samyan
Your example saved me, just used your /types and boom.
Thank you very much. Hope the mantainers take note of the problem

**Comment by GeeWee** [comment]
The typing solution works for me as well - even though it's a global type. It seems to me like if you have different tables with different plugins typing them all globally that way will start to fall apart at some point. I'd love for some way to specify on a per-table basis what plugins the table uses.

**Comment by tostavio** [comment]
Still not working on 7.7. 

- "react-table": "^7.7.0",
- "@types/react-table": "^7.7.1",

`Property 'getSortByToggleProps' does not exist on type 'HeaderGroup<{ firstName: string; lastName: string; age: number; visits: number; progress: number; status: string; }>'.`

OrderBy works but types is not correct.

![image](https://user-images.githubusercontent.com/17911014/123120572-cee0a880-d41a-11eb-9917-7818a84d0544.png)

**Comment by samyan** [comment]
> Still not working on 7.7.
> 
> * "react-table": "^7.7.0",
> * "@types/react-table": "^7.7.1",
> 
> `Property 'getSortByToggleProps' does not exist on type 'HeaderGroup<{ firstName: string; lastName: string; age: number; visits: number; progress: number; status: string; }>'.`
> 
> OrderBy works but types is not correct.
> 
> ![image](https://user-images.githubusercontent.com/17911014/123120572-cee0a880-d41a-11eb-9917-7818a84d0544.png)

Check it https://github.com/tannerlinsley/react-table/issues/2970#issuecomment-756364081

**Comment by kristjaningi** [comment]
Same issue for me. Did manually create the type file as @samyan suggested.

**Comment by christianblandford** [comment]
This saved my project, thanks all

**Comment by finkrer** [comment]
What a weird solution. The types from the readme aren't even the same as those in the package. Adding those definitions breaks existing code.

**Comment by drummerwolli** [comment]
@samyan you're suggestions fix the initial file, but in the types file you provided, typescript now complains about:

`All declarations of 'Row' must have identical type parameters.`
(for each interface declared there)

any ideas how to fix this? thx in advance.

**Comment by alexinfurs** [comment]
> @samyan you're suggestions fix the initial file, but in the types file you provided, typescript now complains about:
> 
> `All declarations of 'Row' must have identical type parameters.` (for each interface declared there, its also happening in your codesandbox)
> 
> any ideas how to fix this? thx in advance.

I fixed by replacing
`Record<string, unknown> = Record<string, unknown>`
with
`object = {}`

**Comment by oylp1988** [comment]
> > > https://codesandbox.io/s/react-table-incomplete-types-forked-0hdd1
> > 
> > 
> > @samyan
> > The sandbox link seems to be not working. I am facing the same issue with ts. After creating a type defination file also I am getting the below error
> > `Parameter 'headerGroup' implicitly has an 'any' type.ts(7006)`
> 
> Updated:
> 
> https://codesandbox.io/s/react-table-incomplete-types-fixed-2r4us

@samyan  Hi Bro, this codesandbox link is not working, can you post your code again pls?

**Comment by samyan** [comment]
> > > > https://codesandbox.io/s/react-table-incomplete-types-forked-0hdd1
> > > 
> > > 
> > > @samyan
> > > The sandbox link seems to be not working. I am facing the same issue with ts. After creating a type defination file also I am getting the below error
> > > `Parameter 'headerGroup' implicitly has an 'any' type.ts(7006)`
> > 
> > 
> > Updated:
> > https://codesandbox.io/s/react-table-incomplete-types-fixed-2r4us
> 
> @samyan Hi Bro, this codesandbox link is not working, can you post your code again pls?

Link restored. Check again pls.

**Comment by oylp1988** [comment]
> > > > > https://codesandbox.io/s/react-table-incomplete-types-forked-0hdd1
> > > > 
> > > > 
> > > > @samyan
> > > > The sandbox link seems to be not working. I am facing the same issue with ts. After creating a type defination file also I am getting the below error
> > > > `Parameter 'headerGroup' implicitly has an 'any' type.ts(7006)`
> > > 
> > > 
> > > Updated:
> > > https://codesandbox.io/s/react-table-incomplete-types-fixed-2r4us
> > 
> > 
> > @samyan Hi Bro, this codesandbox link is not working, can you post your code again pls?
> 
> Link restored. Check again pls.

Thx dude.

**Comment by Arthur-BV** [comment]
> I had a similar issue with another plugin. The solution i got, was creating folder called **types** in **/src** directory and then creating a file called **react-table-config.d.ts**. Then put the definitions that you can find in: [types/react-table](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table).
> 
> Now you can check: ![image](https://user-images.githubusercontent.com/3801362/103941340-fd99e980-512e-11eb-9e36-0bc47d6c6f42.png)
> 
> Example: https://codesandbox.io/s/react-table-incomplete-types-fixed-2r4us
> 
> Regards.

thank you for your method, it was helpful me :)))
how did you figure out it ???

**Comment by Arthur-BV** [comment]
> > > I had a similar issue with another plugin. The solution i got, was creating folder called **types** in **/src** directory and then creating a file called **react-table-config.d.ts**. Then put the definitions that you can find in: [types/react-table](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table).
> > > Now you can check: ![image](https://user-images.githubusercontent.com/3801362/103941340-fd99e980-512e-11eb-9e36-0bc47d6c6f42.png)
> > > Example: https://codesandbox.io/s/react-table-incomplete-types-fixed-2r4us
> > > Regards.
> > 
> > 
> > thank you for your method, it was helpful me :))) how did you figure out it ???
> 
> Going from javascript to typescript, the rest is experience.
> 
> Regards.

You know, that it was only viewer issue, because runtime all code is work !

**Comment by samyan** [comment]
> > > > I had a similar issue with another plugin. The solution i got, was creating folder called **types** in **/src** directory and then creating a file called **react-table-config.d.ts**. Then put the definitions that you can find in: [types/react-table](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-table).
> > > > Now you can check: ![image](https://user-images.githubusercontent.com/3801362/103941340-fd99e980-512e-11eb-9e36-0bc47d6c6f42.png)
> > > > Example: https://codesandbox.io/s/react-table-incomplete-types-fixed-2r4us
> > > > Regards.
> > > 
> > > 
> > > thank you for your method, it was helpful me :))) how did you figure out it ???
> > 
> > 
> > Going from javascript to typescript, the rest is experience.
> > Regards.
> 
> You know, that it was only viewer issue, because runtime all code is work !

Yes, It's right. It simply helps you to know the methods that the library itself has, in addition to visually making the code more elegant.
